name: go_healthy
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-246.0.dev <4.0.0"

# To add dependences we run the command 'flutter pub add {dependance name}' that we can find on pub.dev

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  go_router: ^9.0.0
  google_sign_in: ^6.1.4
  http: ^1.0.0
  intl: any
  lottie: ^2.4.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter to analyze your code and make it cleaner (listen to it please :D)
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  # Pour ajouter des assets à l'application il faut ajouter le chemin relatif:
  assets:
    # Add assets from the images directory to the application.
    - .env
    - assets/images/
    - assets/lottie/

  # Pour ajouter des polices de caractères à l'application il faut ajouter le chemin relatif et le nom de la police:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans_10pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans_10pt-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NunitoSans_10pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans_10pt-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NunitoSans_10pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans_10pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NunitoSans_10pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans_10pt-BoldItalic.ttf
          weight: 700
          style: italic
  #   - family: fontNameRegular
  #     fonts:
  #       - asset: fonts/fontNameRegular.ttf
  #       - asset: fonts/fontNameRegularItalic.ttf
  #         style: italic
  #   - family: fontNameBold
  #     fonts:
  #       - asset: fonts/fontNameBold.ttf
  #       - asset: fonts/fontWeightBoldItalic.ttf
  #         weight: 700
  #         style: italic
